<?php

namespace Database\Seeders;

use App\Models\ApplicationSystem;
use Illuminate\Database\Seeder;

class ApplicationSystemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $systems = [
            'Hospital Advisor (hospital Advisor)',
            'Hospital Operations And Management Information System (homis)',
            'Integrated Chronic Non-communicable Disease Registry System (chronic)',
            'Integrated Clinic Information System (iclinicsys)',
            'Integrated Doh Licensing Information System (licensing)',
            'Integrated Drug Abuse Data And Information Network (idadin) - Form 6-06 (idadin)',
            'Integrated Drug Test Operation And Management Information System (idtomis)',
            'Financial Management Reporting System Phase 1 (engas)',
            'Fireworks Related Respiratory Illness Surveillance System (frriss)',
            'Foreign Surgical And Medical Mission Of The Philippines (fsmmp)',
            'Health Emergency Preparedness And Response Information System (heris)',
            'Health Facility Enhancement Program Tracking System (hfepts)',
            'Hems Web Portal And Database (hems Web Portal)',
            'Hiv/aids Registry (hiv/aids)',
            'Drug Price Watch (dpw)',
            'Enhanced Field Health Services Information System (efhsis)',
            'Enhanced Travel Monitoring System (tms)',
            'Environmental Health (esis)',
            'Event Based Surveillance Reporting System (esr)',
            'Event Registration System/activity Registration (activityregistration)',
            'Expenditure Tracking System (expenditure Tracking)',
            'Bellygud For Health (bellygud)',
            'Bfad Integrated Information System (bfad)',
            'Community Health Team Information System (webbased) (community Health)',
            'Database Of Rational Use Of Anti-biotics (antibiotics)',
            'Development Partners And Technical Assistance Portal (dptap)',
            'Doh Attendance System Using Biometrics - Finger Scanning Device (biometrics)',
            'Doh Intranet (doh Intranet)',
            'Admin Issuance System (old Doh Billboard)',
            'Adverse Drug Reaction System (adverse)',
            'Annual Hospital Statistical Reporting System (ohsrs)',
            'Application Of Inclusion/exclusion Pnf (pnf)',
            'Application Systems Checker (asc)',
            'Asean Getting To Zero (aids Survey Data)',
            'Personnel Information System (pis)',
            'Philippine Health Atlas (mapping Server) (health Atlas)',
            'Philippine Integrated Disease Surveillance System And Response (pidsr)',
            'Philippine Network Injury Data Management System (pnidms)',
            'Philippine Organ Donor And Recipient Registry System (organ Donor)',
            'Philippine Registry For Persons With Disability (prpwd)',
            'Procurement Operation And Management Information System (pomis)',
            'Property Accountability And Monitoring System (pams)',
            'National Rabies Information System (naris)',
            'National Telehealth Service Program (ntsp)',
            'R4health Telemedicine (ntsp)',
            'Nchp Monitoring And Evaluation System (m&e)',
            'Neglected Tropical Disease (ntd)',
            'New Issuance Billboard (issuance Billboard)',
            'Online Document Tracking Information System (dtis)',
            'Online National Electronic Injury Surveillance System (oneiss)',
            'Online Yellow Prescription Pad System (yellow Prescription)',
            'National Blood Bank Network System (nbbnets)',
            'National Database For Human Resouce For Health Information System (hrhis)',
            'National Drug Information System (ndis)',
            'National Health Atlas/philippine Health Atlas (nhagis)',
            'National Health Data Dictionary (nhdd)',
            'National Health Facility Registry (nhfr)',
            'National Online Stock Inventory And Reporting System (nosirs)',
            'Loan Remittance Certificate Information System (loan Remittance)',
            'Local Health Information System (Ihis)',
            'Maternal And Neonatal Death Reporting System (mndrs)',
            'Medical Assistance Program (map)',
            'Medical Tourism (medical Tourism)',
            'Mmda Injury Reporting System (mmdairs)',
            'Monitoring The Violations Of 100% Smoke Free Philippines (100% Smoke Free)',
            'National Barangay Health Worker (bhw) Registry System (bhw)',
            'Integrated E-library System (athena) (athena)',
            'Integrated Payroll System (payroll)',
            'Integrated Procurement Logistics Information System (iplmis)',
            'Integrated Tb Information System (itis)',
            'Inventory Of Information System (iis)',
            'Kp Dashboard (kp Dashboard)',
            'Ched Injury Reporting (chedir)',
            'Covid Documents Repository System (cdrs)',
            'Drug Price Reference Index (dpri)',
            'Electronic Drug Price Monitoring System (edpms)',
            'Notice Of Meeting (nom)',
            'Ofw System (ofw)',
            'Online Service Request System (srs)',
            'Watching Over Mothers And Babies (womb)',
            'Web Based Public Assistance Information System (webpais)',
            'Work Assignment Monitoring System (wams)',
            'Yolanda Task-force System Modules (task-force Yolanda)',
            'Doh Ejobs System (ejobs)',
            'Doh Website (doh Website)',
            'Ssed Website (ssed)',
            'Quarantine Services And International Health Surveillance System (qsihss)',
            'Resource Center For Health System Development (rchsd)',
            'Schistosomiasis Information System (nueroschisto Registy)',
            'Surveillance In Post Extreme Emergencies And Disasters (speed)',
            'Tor Clearance System (tor)',
            'Training Information System (tis)',
            'Unified Health Management Information System (uhmis)',
            'Violence Against Women And Children Registry System (vawcrs)',
            'KMITS Info Systems',
            'Cancer Assistance Fund Information System',
            'Cancer Supportive-Palliative Medical Access Program',
            'COVID-19 Compensation Assessment System',
            'COVID-19 Supply Management Tracking System',
            'Depot Online Stock and Inventory Reporting System',
            'DOH Employee Health Information System',
            'DOH Intranet',
            'Drug Abuse and Treatment and Rehabilitation Information System',
            'Fireworks Related Injury Surveillance System',
            'Foreign Assistance Management Information System',
            'General Services System (Vehicle request and Repair and Maintenance)',
            'Health Emergency Allowance Processing System',
            'Health Facilities Enhancement Program Tracking System',
            'Health Facility Price Advisory Application',
            'Integrated Chronic Non-communicable Disease Registry',
            'Integrated Clinic Information System',
            'Integrated Drug Test Operations and Management Information System',
            'Integrated Hospital Operations and Management Information System',
            'Integrated Leprosy Information System',
            'Maternal, Neonatal and Infant Death Reporting System',
            'Medical Assistance Information System',
            'National eHealth Electronic Health Records System Validation',
            'National External Quality Assurance Scheme',
            'National Rabies Information System',
            'Neglected Tropical Disease Management Information System',
            'Online Bidding Documents Payment System',
            'Online Health Facility Statistical Reporting System',
            'Online National Electronic Injury Surveillance System',
            'Online Property Accountability Management System',
            'Personnel Transaction Information System (PTIS)',
            'Philippine Organ Donor and Recipient Registry System',
            'Philippine Registry for Persons with Disabilities',
            'Philippine Renal Disease Registry',
            'PITAHC Project Research Management Information System',
            'POMIS Forum Site',
            'Procurement Operations Management Information System',
            'Quality Management System Portal',
            'Quarantine Services and International Health Surveillance System',
            'Sumbungan Board (Health Facilities Oversight Board) Website',
            'Violence Against Women and Children Registry',
            'Internal Audit Services Document Management System',
            '7th Global Ministerial Summit Patient Safety',
            'Legal Service Document Information System',
            'Cart Client Concern Management System',
            'MAIFIP Program Information System',
            'Health Impact Assesment Application System (HIAPPS)',
            'Standards Conformance and Interoperability Validation System',
            'Chronic Obstructive Pulmonary Disease Registry',
            'Dengue Vaccine Surveillance System',
            'National Health Data Dictionary System',
            'Unified Intake Sheet Portal',
            'Foreign-Assisted Projects Monitoring and Evaluation System (FAPMES)',
            'DOH Health Research Repository System',
            'One Plan Information System (OPIS)',
            'Careers for Health (CFH)',
            'Maternal, Neonatal Death Reporting System',
            'Integrated Tuberculosis Information System',
        ];

        foreach ($systems as $name) {
            $trimmed = trim($name);
            if ($trimmed === '') {
                continue;
            }

            ApplicationSystem::query()->updateOrCreate(
                ['name' => $trimmed],
                ['is_active' => true]
            );
        }
    }
}
